'use client'

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   if ('serviceWorker' in navigator) {
  //     window.addEventListener('load', () => {
  //       navigator.serviceWorker.register('/sw.js')
  //         .then(reg => console.log('SW registered:', reg))
  //         .catch(err => console.log('SW registration failed:', err));
  //     });
  //   }
  // }, []);

  return (
    <html lang="en">
      <head>
        {/* 链接 Manifest 文件 */}
        <link rel="manifest" href="/manifest.json" />

        {/* 设置主题颜色 */}
        <meta name="theme-color" content="#0070f3" />

        {/* 添加 Apple Touch Icon (可选，为了更好的 iOS 支持) */}
        <link rel="apple-touch-icon" href="/icons/home.png" />

        {/* 更多 PWA 相关的 Meta 标签 (根据需要添加) */}
        <meta name="application-name" content="NextPWA" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="NextPWA" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        {/* <meta name="msapplication-config" content="/icons/browserconfig.xml" /> */}
        <meta name="msapplication-TileColor" content="#0070f3" />
        <meta name="msapplication-tap-highlight" content="no" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
